### ISSUE TITLE
i am newer,how this project run,

### ISSUE THREAD

**Issue by 254347458** [lab2023/hierapolis#52]

**Comment by tayfunoziserikan** [comment]
Hi, 

This project uses [Middleman](http://middlemanapp.com/) You can find more information about middleman here: http://middlemanapp.com/basics/getting-started/

If you need css and js files you can use `middleman build` command.

**Comment by 254347458** [comment]
can you give more detail？

------------------ 原始邮件 ------------------
发件人: "Tayfun &#xD6;zi&#x15F; ER&#x130;KAN"notifications@github.com; 
发送时间: 2014年11月10日(星期一) 中午1:28
收件人: "lab2023/hierapolis"hierapolis@noreply.github.com; 
抄送: "盐水"254347458@qq.com; 
主题: Re: [hierapolis] i am newer,how this project run, (#52)

Hi, 

This project uses Middleman You can find more information about middleman here: http://middlemanapp.com/basics/getting-started/

If you need css and js files you can use middleman build command.

**Comment by onurozgurozkan** [comment]
You can find HTML Output at https://github.com/lab2023/hierapolis/tree/gh-pages .
