### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by kamleshchandnani** [lab2023/hierapolis#57]
I am using windows Os now how to use these commands? i have tried middleman from gitshell windows and it gives below error!!Also bundle install is not working how to make these things work?

middleman : The term 'middleman' is not recognized as the name of a cmdlet, function, script file, or operable
program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
- middleman build
- ~~~~~~~~~
  - CategoryInfo          : ObjectNotFound: (middleman:String) [], CommandNotFoundException
  - FullyQualifiedErrorId : CommandNotFoundException

**Comment by pzyyll** [comment]
middleman build

**Comment by abdihaikal** [comment]
Do you already have Ruby and Bundler installed?
For Window OS, you can get:
- RubyInstaller at http://rubyinstaller.org/
- Bundler at http://bundler.io/

**Comment by onurozgurozkan** [comment]
You can find HTML code at https://github.com/lab2023/hierapolis/tree/gh-pages gh-pages branch.
